In [39]:
import numpy as np
from rules import *

card_path = './cards.csv'
nobles_path = './nobles.csv'
cards = np.genfromtxt(card_path, dtype=np.int32, delimiter=',', skip_header=1)
nobles = np.genfromtxt(nobles_path, dtype=np.int32, delimiter=',', skip_header=1)

In [40]:
print(cards[:10])

[[1 0 1 0 2 1 0 0]
 [1 0 2 0 0 0 1 2]
 [1 0 3 0 1 0 2 0]
 [1 0 4 2 0 0 0 1]
 [1 0 5 1 0 2 0 0]
 [1 0 1 0 0 0 0 3]
 [1 0 2 0 0 3 0 0]
 [1 0 3 0 0 0 3 0]
 [1 0 4 3 0 0 0 0]
 [1 0 5 0 3 0 0 0]]


In [41]:
print(nobles)

[[4 0 4 0 0]
 [4 0 0 0 4]
 [0 0 0 4 4]
 [0 4 0 4 0]
 [0 4 4 0 0]
 [3 3 3 0 0]
 [3 0 3 0 3]
 [3 0 0 3 3]
 [0 3 0 3 3]
 [0 3 3 3 0]]


In [42]:
board = Board()
print(board.nobles[0])
print(board.all_cards[1])